@startuml

title __TFA-DAP's Class Diagram__\n

  namespace  {
    class Client {
    }
  }
  

  namespace  {
    namespace odelo {
      class modelo.Player {
      }
    }
  }
  

  namespace  {
    namespace odelo {
      enum Result {
      }
    }
  }
  

  namespace  {
    namespace odelo {
      class modelo.Team {
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        abstract class modelo.datafinder.DataFetcherStrategy {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.PruebaDataFetcher {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyContext {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyGames {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyPlayer {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyTeam {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyTeamPlayers {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyTeamStandings {
        }
      }
    }
  }
  

  namespace  {
    namespace odelo {
      namespace datafinder {
        class modelo.datafinder.StrategyTeamStats {
        }
      }
    }
  }
  

  modelo.datafinder.StrategyContext o-- modelo.datafinder.DataFetcherStrategy : strategy
  modelo.datafinder.StrategyGames -up-|> modelo.datafinder.DataFetcherStrategy
  modelo.datafinder.StrategyPlayer -up-|> modelo.datafinder.DataFetcherStrategy
  modelo.datafinder.StrategyTeam -up-|> modelo.datafinder.DataFetcherStrategy
  modelo.datafinder.StrategyTeamPlayers -up-|> modelo.datafinder.DataFetcherStrategy
  modelo.datafinder.StrategyTeamStandings -up-|> modelo.datafinder.DataFetcherStrategy
  modelo.datafinder.StrategyTeamStats -up-|> modelo.datafinder.DataFetcherStrategy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
