@startuml

title __MODELO's Class Diagram__\n

  namespace TFA {
    namespace modelo {
      class TFA.modelo.NBAModel {
          {static} - instance : NBAModel
          - teamsList : ArrayList<Team>
          {static} + getInstance()
          + getTeamsList()
          + setTeamList()
          - NBAModel()
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.Player {
          - id : int
          - name : String
          - number : int
          - position : String
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.PruebaModel {
          {static} + main()
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      enum Result {
        LOSE
        WIN
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.Team {
          ~ results : HashMap<Result, Integer>
          - conference : String
          - crestUrl : String
          - fieldGoalsPercentage : float
          - freeThrowsPercentage : float
          - gamesPlayed : int
          - id : int
          - name : String
          - players : ArrayList<Player>
          - points : int
          - ranks : int
          - shortName : String
          - threePointsPercentage : float
          + Team()
          + getConference()
          + getCrestUrl()
          + getId()
          + getName()
          + getShortName()
          + setConference()
          + setCrestUrl()
          + setId()
          + setName()
          + setShortName()
      }
    }
  }
  

  TFA.modelo.NBAModel o-- TFA.modelo.datafinder.StrategyContext : strategyContext


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
