@startuml

title __MODELO's Class Diagram__\n

  namespace TFA {
    namespace modelo {
      class TFA.modelo.NBAModel {
          {static} - instance : NBAModel
          - teamsMap : HashMap<String, Integer>
          {static} + getInstance()
          + getTeamByName()
          + getTeamsList()
          + setPlayersListFromTeam()
          + setTeamList()
          + setTeamStanding()
          - NBAModel()
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.Player {
          - id : int
          - jersey : String
          - lastName : String
          - name : String
          - position : String
          + Player()
          + printInfo()
          + toString()
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.PruebaModel {
          {static} + main()
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      enum Result {
        LOSS
        WIN
      }
    }
  }
  

  namespace TFA {
    namespace modelo {
      class TFA.modelo.Team {
          ~ results : HashMap<Result, Integer>
          - conference : String
          - crestUrl : String
          - defensiveRebounds : int
          - fieldGoalsAttempted : int
          - fieldGoalsMade : int
          - freeThrowsAttempted : int
          - freeThrowsMade : int
          - gamesPlayed : int
          - id : int
          - name : String
          - offensiveRebounds : int
          - players : ArrayList<Player>
          - points : int
          - rank : int
          - shortName : String
          - steals : int
          - threePointsAttempted : int
          - threePointsMade : int
          - totalRebounds : int
          - turnovers : int
          + Team()
          + addResult()
          + getConference()
          + getCrestUrl()
          + getId()
          + getName()
          + getPlayers()
          + getShortName()
          + setPlayers()
          + setRank()
      }
    }
  }
  

  TFA.modelo.NBAModel o-- TFA.modelo.datafinder.StrategyContext : strategyContext


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
